on: [push, pull_request]

name: Test
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31

  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      # Quotes for "-coverprofile=cover.out" are required for Windows because of the "." in the argument name.
      run: go test -v -covermode=atomic "-coverprofile=profile.cov" ./...
    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      if: matrix.os == 'ubuntu-latest' && matrix.go-version == '1.15.x'
      with:
        path-to-profile: profile.cov
